services:
  - type: web
    name: felix-travel-tv-api
    runtime: node
    buildCommand: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm -r --filter @workspace/db --filter @workspace/api-zod --filter @workspace/integrations-openai-ai-server --filter @workspace/api-server build
    startCommand: node --enable-source-maps ./artifacts/api-server/dist/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: TRAVEL_TV_OPEN_AI_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: felix-travel-tv-db
          property: connectionString

databases:
  - name: felix-travel-tv-db
    plan: standard
