// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tv-slide/BroadcastSlide.tsx": () => import("../components/mockups/tv-slide/BroadcastSlide.tsx")
};
